### ISSUE TITLE
Assignment 8 complete

### ISSUE THREAD

**Issue by eelmstrom** [eelmstrom/Assignment-8#1]
Apologies for the delay! 

Still having trouble adding Mark to the issue. :/ But hopefully this is all good.

**Comment by mdscheuerell** [comment]
No worries—this is great.

And b/c you asked [here](https://github.com/eelmstrom/Assignment-8/blob/aaf92a772be4e54f72387f0ca6040614ad4c7708/Assignment-8.Rmd#L43), creating a pkg for each publication would be great, but having everything spelled out in a well-structured compendium would seem adequate in many cases. If you're interested, you might want to go back and check out some of [these options](https://fish497.github.io/website/lectures/week_01/lec_03_orgs_styles.html#21).
